In [19]:
import pandas as pd

In [20]:
table_name = 'WP_Vendor'
df_WP_Vendor = pd.read_csv(f"all_tables/{table_name}.csv")    
print(df_WP_Vendor.shape[0])        
display(df_WP_Vendor.tail(4))

748

,UID,WorkPackageId,VendorName,VendorContact,VenddorEmail
744,760,52095,Aspect Studios,Kirsten Bauer,kirsten.bauer@aspect-studios.com
745,761,52095,Glas Urban,Mark Gillingham,mgillingham@glasurban.com
746,762,52095,Oculus,Claire Martin,claire@oculus.info
747,763,52095,Urban Initiatives,Ian Robertson,ian@urbaninitiatives.com.au

In [21]:
df_WP_Vendor[df_WP_Vendor['WorkPackageId'] == 51787]

,UID,WorkPackageId,VendorName,VendorContact,VenddorEmail
679,695,51787,JMA Architects,Nick Millar,nickm@jmarchitects.com.au
680,696,51787,NA Architects,Nicholas Daviotis,naarch@bigpond.net.au
681,697,51787,Vincent Chrisp Architects,Jim Chrisp,jc@vincentchrisp.com.au

In [ ]:
df_WP_Vendor

In [11]:
table_name = 'PR_WORK_PACKAGES'
df_PR_WORK_PACKAGES = pd.read_csv(f"all_tables/{table_name}.csv")    
print(df_PR_WORK_PACKAGES.shape[0])        
display(df_PR_WORK_PACKAGES.tail(5))

22196

,UID,PR_UID,TITLE,COST_CODE,PROCUREMENT_TYPE,STATUS,ORDER_NUMBER,SUPPLIER_COMPANY,ORDER_DATE,ORIGINAL_CONTRACT,...,FFC_CHANGE,CC_LAST,CONTRACT_TYPE_ID,ENGAGEMENT_TYPE_ID,IS_CA_TRACKING_REQUIRED,APPROVAL_ID,APPROVAL_ID_ASSIGN_VALUE,CONTINGENCY,BR_CALCULATION,TRANSITION_ID
22191,52146,1505,299 - Construction Contingency,11,116.0,111.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22192,52147,1505,399 - Other Project Costs Contingency,27,116.0,111.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22193,52148,1505,309 -Miscellaneous Project Costs,20,116.0,111.0,9999-1505,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22194,52149,1505,401 - Project Contingency,21,116.0,111.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22195,52150,1505,400 - Reservered Proejct Contigency,29,116.0,111.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_a = df_PR_WORK_PACKAGES[['UID','PR_UID','TITLE']]

In [16]:
df_b = df_WP_Vendor[['WorkPackageId', 'VendorName']]

In [18]:
df_a.merge(df_b, left_on='UID', right_on='WorkPackageId')

,UID,PR_UID,TITLE,WorkPackageId,VendorName
0,29968,291,301 - ITS,29968,11
1,29968,291,301 - ITS,29968,22
2,39374,301,202 Main Works Contractor,39374,aa
3,39374,301,202 Main Works Contractor,39374,bb
4,40016,794,107.02 - Building Surveyor,40016,Steve Watson & Partners
5,40016,794,107.02 - Building Surveyor,40016,Boswell Shaw Giazi Marshall Pty Ltd
6,40016,794,107.02 - Building Surveyor,40016,McKenzie
7,40016,794,107.02 - Building Surveyor,40016,Du Chateau
8,40025,794,202.00 - Construction General,40025,Probuild Constructions (Aust)
9,40025,794,202.00 - Construction General,40025,Lendlease Building Contractors
10,40025,794,202.00 - Construction General,40025,Multiplex Constructions
11,40389,816,202.00 - Network Programming,40389,Blue Fire Systems
12,40389,816,202.00 - Network Programming,40389,Thermal Fire Protection
13,40602,663,202.00 - EWIS Caulfield,40602,Blue Fire Systems
14,40602,663,202.00 - EWIS Caulfield,40602,Thermal Fire Protection
15,40696,794,107.09 - DDA Consultant,40696,Equal Access Pty Ltd
16,40696,794,107.09 - DDA Consultant,40696,Architecture & Access
17,40696,794,107.09 - DDA Consultant,40696,Philip Chun
18,42503,632,202.00 - Construction Phase 2 Ground Floor,42503,Kane Constructions ( Vic ) Pty Ltd
19,42503,632,202.00 - Construction Phase 2 Ground Floor,42503,Harris HMC Pty Ltd
20,42503,632,202.00 - Construction Phase 2 Ground Floor,42503,Hutchinson Builders Pty Ltd
21,42503,632,202.00 - Construction Phase 2 Ground Floor,42503,Neo Construct
22,43579,940,202.00 - Construction General,43579,Built
23,43579,940,202.00 - Construction General,43579,Icon Cockram
24,43579,940,202.00 - Construction General,43579,Kane
25,43579,940,202.00 - Construction General,43579,Multiplex
26,43579,940,202.00 - Construction General,43579,Watpac
27,43591,940,302.00 - Audio Visual,43591,CHW
28,43591,940,302.00 - Audio Visual,43591,NDY
29,43591,940,302.00 - Audio Visual,43591,WSP
...,...,...,...,...,...
718,51717,1185,202.00 - Construction General,51717,Alchemy Construct
719,51717,1185,202.00 - Construction General,51717,Arete (Kane Constructions)
720,51717,1185,202.00 - Construction General,51717,Neo Construct
721,51717,1185,202.00 - Construction General,51717,United Commercial Projects
722,51735,1476,101.00 - Architect,51735,Brand Architects
723,51735,1476,101.00 - Architect,51735,DS Architects
724,51735,1476,101.00 - Architect,51735,JMA Architects
725,51736,1476,102.00 - Engineering building services,51736,Braird Engineers
726,51736,1476,102.00 - Engineering building services,51736,Lucid Consulting
727,51736,1476,102.00 - Engineering building services,51736,TNC Consultancy
728,51787,1477,101.00 - Architect (GFC),51787,JMA Architects
729,51787,1477,101.00 - Architect (GFC),51787,NA Architects
730,51787,1477,101.00 - Architect (GFC),51787,Vincent Chrisp Architects
731,51810,1475,102.00 - Engineering building services,51810,GHD
732,51810,1475,102.00 - Engineering building services,51810,Irwinconsult
733,51810,1475,102.00 - Engineering building services,51810,Lehr Consultants International
734,51810,1475,102.00 - Engineering building services,51810,Lucid Consulting
735,51812,1475,107.00 - Audio Visual engineer Consultant,51812,CHW Consulting
736,51812,1475,107.00 - Audio Visual engineer Consultant,51812,Norman Disney & Young
737,51826,1492,202.00 - Construction General,51826,Alchemy Construct
738,51826,1492,202.00 - Construction General,51826,Baxter Projects
739,51826,1492,202.00 - Construction General,51826,Kapitol Group
740,51846,1116,201.04 - Demolition Early Works,51846,Aptum Aldridge
741,51846,1116,201.04 - Demolition Early Works,51846,Bernie Leen & Sons
742,51846,1116,201.04 - Demolition Early Works,51846,City Circle Demolition
743,51846,1116,201.04 - Demolition Early Works,51846,Delta
744,52095,1474,101.00 - Landscape Architect,52095,Aspect Studios
745,52095,1474,101.00 - Landscape Architect,52095,Glas Urban
746,52095,1474,101.00 - Landscape Architect,52095,Oculus
747,52095,1474,101.00 - Landscape Architect,52095,Urban Initiatives